name: Regression Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Run regression tests
        run: mvn test -Dtest=CalculatorTest

      - name: Generate test report
        run: mvn surefire-report:report

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: target/site/surefire-report.html

      - name: Archive Calculator file
        uses: actions/upload-artifact@v2
        with:
          name: Calculator File
          path: Calculator.java
