name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: 11
         distribution: adopt


      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test -Dtest=CalculatorTest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
 
      - name: Build and test
        run: |
          mvn clean install

      manual-approval:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Manual approval for production deployment
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main&head=${{ github.sha }}")
          
          prs=$(echo "$response" | jq length)
          
          if [[ $prs -gt 0 ]]; then
            echo "There are open pull requests targeting this branch. Manual approval is required."
            exit 1
          fi

  
     

     
