name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: 11
         distribution: adopt


      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test -Dtest=CalculatorTest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
 
      - name: Build and test
        run: |
          mvn clean install

      - name: Set up Git
        run: |
          git config --global user.name "Sreevaishnavisadhasivam"
          git config --global user.email "sreevaishnavi2002@gmail.com"

      - name: Check out gh-pages branch
        run: git checkout -B gh-pages

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Update gh-pages"

      - name: Set remote origin
        run: git remote add origin "https://github.com/Sreevaishnavisadhasivam/test.git"

      - name: Push to gh-pages branch
        run: git push origin gh-pages
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  
     

     
