name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: 11
         distribution: adopt


      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test -Dtest=CalculatorTest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
 
      - name: Build and test
        run: |
          mvn clean install

      - name: Push to gh-pages
        run: |
          git config --global user.name "Sreevaishnavisadhasivam"
          git config --global user.email "sreevaishnavi2002@gmail.com"
          git checkout gh-pages
          git add .
          git commit -m "Update gh-pages"
          git remote remove origin
          git remote add origin "https://github.com/Sreevaishnavisadhasivam/test.git"
          git push origin gh-pages
          env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  
     

     
